package com.pm.patientservice.model;

import java.time.LocalDate;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotNull;
import jakarta.persistence.GenerationType;

// This class is entity class
@Entity
public class Patient {
    // we're saying : the UUID is going to be the id of patient entity (autogenerated by database)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;

    // fails if name does not have a value
    @NotNull
    private String name;

    // adding other validations(straightforward)
    @NotNull
    @Email
    @Column(unique = true)
    private String email;

    @NotNull
    private String address;

    @NotNull
    private LocalDate dateOfBirth;

    @NotNull
    private LocalDate registeredDate;

    // Getter and Setter (encapsulation, good practice instead of direct access)
    public UUID getId(){
        return id;
    }

    public void setId(UUID id){
        this.id = id;
    }

    public @NotNull String getName(){
        return name;
    }
    
    public void setName(@NotNull String name){
        this.name = name;
    }

    public @NotNull @Email String getEmail(){
        return email;
    }

    public void setEmail(@NotNull @Email String email){
        this.email = email;
    }

    public @NotNull String getAddress(){
        return address;
    }
    
    public void setAddress(@NotNull String address){
        this.address = address;
    }

    public @NotNull LocalDate getDateOfBirth(){
        return dateOfBirth;
    }

    public void setDateOfBirth(@NotNull LocalDate dateOfBirth){
        this.dateOfBirth = dateOfBirth;
    }

    public @NotNull LocalDate getRegisteredDate(){
        return registeredDate;
    }

    public void setRegisteredDate(@NotNull LocalDate registeredDate){
        this.registeredDate = registeredDate;
    }

}
